import { useCallback, useEffect, useState } from 'react';
import { Avatar, Button, Spinner } from '@fluentui/react-components';
import { Add24Regular, Alert24Regular, ArrowExit20Regular, ArrowRight24Regular, BookOpen24Regular, Briefcase24Regular, CheckmarkCircle24Regular, ChevronRight20Regular, Clock24Regular, History24Regular, Home24Regular, Navigation24Regular, PeopleTeam24Regular, Person24Regular, Scales24Regular, Search24Regular, ShieldTask24Regular, Sparkle24Regular, TaskListSquareLtr24Regular } from '@fluentui/react-icons';
import { api, post, roleNames, dateText, timeLeft } from './api';
import type { User, CaseItem, Task, AuditLog } from './api';
import { CaseWorkspace } from './CaseWorkspace';
import { KnowledgePage, Login } from './Pages';
import { Intake } from './Intake';

export function RiskBadge({ risk }: { risk: string }) { return <span className={`risk risk-${risk === '高' ? 'high' : risk === '低' ? 'low' : 'medium'}`}><i />{risk}风险</span>; }
export function Heading({ title, description, actions }: { title: string; description: string; actions?: React.ReactNode }) { return <div className="page-heading"><div><h1>{title}</h1><p>{description}</p></div>{actions && <div className="heading-actions">{actions}</div>}</div>; }
export function Empty({ title = '暂无记录', description = '完成上一步操作后，相关内容会显示在这里。' }: { title?: string; description?: string }) { return <div className="empty"><Briefcase24Regular /><strong>{title}</strong><p>{description}</p></div>; }
export function Brand({ light = false }: { light?: boolean }) { return <div className={`brand ${light ? 'brand-light' : ''}`}><div className="brand-icon"><ShieldTask24Regular /></div><div><strong>顺丰 · 案盾 <em>AI</em></strong><span>纠纷取证与法律处置</span></div></div>; }

function AiEnginePanel({cases}: {user:User;cases:CaseItem[];openCase:(id:string)=>void}) {
  const analyzed=cases.filter(c=>c.analysis),enhanced=analyzed.filter(c=>c.analysis.mode==='llm');
  return <div className="ai-assist-strip"><Sparkle24Regular/><span><strong>AI 已融入处理流程</strong> 建案后自动分类、提醒固证，并给出有来源的处置建议。</span><span className="mode-badge">{enhanced.length?'已使用模型辅助':'本地辅助可用'}</span></div>;
}

function Workbench({ user, cases, tasks, openCase, newCase, search, setSearch }: { user: User; cases: CaseItem[]; tasks: Task[]; openCase: (id: string) => void; newCase: () => void; search: string; setSearch: (s: string) => void }) {
  const [filter, setFilter] = useState(user.role==='legal'?'法务处理中':'全部案件');
  const [sort, setSort] = useState('risk');
  const active = cases.filter(c => c.status !== '已归档');
  const pending = tasks.filter(t => t.status !== '已完成').sort((a, b) => Date.parse(a.dueAt) - Date.parse(b.dueAt));
  const urgent = pending.filter(t => Date.parse(t.dueAt) - Date.now() <= 86400000 * 2);
  const incoming = active.filter(c=>c.handoffStatus === (user.role==='supervisor'?'awaiting_supervisor':user.role==='legal'?'awaiting_legal':'returned_to_courier'));
  const mine = active.filter(c=>c.currentHandlerId===user.id && !c.handoffStatus?.startsWith('awaiting_'));
  const transferTasks = pending.filter(t => /主管|法务|接收|审核|转交|退回/.test(t.title + t.kind));
  const priority = pending.find(t => t.priority === 'P0') || pending[0];
  const ranks: Record<string,number> = {高:0,中:1,低:2};
  const roleCopy = {
    courier: { kicker: '一线快递员 · 现场处置', title: '我的现场工作台', description: '先把快件、沟通和现场证据留住；自己能闭环的先处理，无法确认再转交主管。', duty: '发现即固证，先处理再升级', flow: '你负责第一时间建案、上传原始材料、回答澄清问题；遇到责任边界或协商卡点，在案件内发起主管审核。', queue: '我的案件队列', focus: '待我完成的固证与客户沟通', action: '新建纠纷案件' },
    supervisor: { kicker: '网点 / 区域主管 · 协同指挥', title: '网点案件指挥台', description: '审阅一线转交的事实与证据，推动网点处置；达到升级条件时，把完整材料交给法务。', duty: '复核事实，决定是否请求法务', flow: '你负责接收快递员转交、补充网点侧证据、确认协商或赔偿路径；重大、高金额、刑事风险或无法判断时请求法务。', queue: '网点案件队列', focus: '待主管复核与网点期限', action: '新建纠纷案件' },
    legal: { kicker: '集团法务 · 人工决策', title: '法务接收与复核台', description: '接收主管提交的案件，核验来源与法律依据，给出可追溯的处置意见和文书草稿。', duty: '人工审核，锁定最终法律口径', flow: '接收主管上报和自动分流案件，给出审核意见；普通业务由快递员和主管自行处理。', queue: '待法务接收与复核队列', focus: '待接收、待审核和来源核验', action: '' },
  }[user.role];
  const filtered = cases.filter(c => (filter === '全部案件' || (filter === '高风险' ? c.risk === '高' && c.status !== '已归档' : filter === '待补证' ? c.completeness < 100 && c.status !== '已归档' : filter === '已归档' ? c.status === '已归档' : c.escalated && c.status !== '已归档')) && (c.title + c.waybill + c.id + c.ownerName).toLowerCase().includes(search.toLowerCase())).sort((a, b) => sort === 'new' ? Date.parse(b.createdAt) - Date.parse(a.createdAt) : (a.status === '已归档' ? 1 : 0) - (b.status === '已归档' ? 1 : 0) || (ranks[a.risk]??3)-(ranks[b.risk]??3));
  const completion = cases.length ? Math.round(cases.reduce((s, c) => s + c.completeness, 0) / cases.length) : 0;
  const metrics = user.role === 'courier'
    ? [{label:'我的进行中',value:active.length,note:'只显示本人负责案件',icon:<Briefcase24Regular/>},{label:'待立即固证',value:pending.filter(t=>t.kind==='evidence').length,note:'先处理时间敏感材料',icon:<ShieldTask24Regular/>,tone:'red'},{label:'48 小时内到期',value:urgent.length,note:'监控、保险与举证期限',icon:<Clock24Regular/>,tone:'amber'},{label:'已具备完整度',value:completion + '%',note:'上传原件才计入完整度',icon:<CheckmarkCircle24Regular/>,tone:'green'}]
    : user.role === 'supervisor'
      ? [{label:'网点进行中',value:active.length,note:'本组织案件总览',icon:<Briefcase24Regular/>},{label:'待主管复核',value:incoming.length,note:'接收快递员转交',icon:<PeopleTeam24Regular/>,tone:'amber'},{label:'法务协同中',value:active.filter(c=>c.currentHandlerRole==='legal').length,note:'高金额 / 重大 / 刑事线索',icon:<Scales24Regular/>,tone:'red'},{label:'平均证据完整度',value:completion + '%',note:'推动网点闭环',icon:<CheckmarkCircle24Regular/>,tone:'green'}]
      : [{label:'待法务接收',value:incoming.length,note:'主管提交的案件',icon:<Scales24Regular/>,tone:'red'},{label:'人工复核中',value:active.filter(c=>c.handoffStatus==='legal_handling').length,note:'责任与赔偿口径锁定',icon:<ShieldTask24Regular/>,tone:'amber'},{label:'来源待核验',value:cases.filter(c=>c.analysis?.citations?.length===0).length,note:'不引用无来源材料',icon:<BookOpen24Regular/>},{label:'平均证据完整度',value:completion + '%',note:'全量案件视图',icon:<CheckmarkCircle24Regular/>,tone:'green'}];
  return <>
    <Heading title={roleCopy.title} description={roleCopy.description} actions={roleCopy.action ? <Button appearance="primary" size="large" icon={<Add24Regular />} onClick={newCase}>新建纠纷案件</Button> : undefined} />
    <div className={"quick-start-grid role-quick-"+user.role}>{[{title:user.role==='courier'?'我要处理新纠纷':user.role==='supervisor'?'接收一线上报':'接收法律咨询',description:user.role==='courier'?'讲清发生了什么，系统带你固证':incoming.length+' 起案件等待你接收',icon:user.role==='courier'?<Add24Regular/>:<PeopleTeam24Regular/>,action:()=>user.role==='courier'?newCase():incoming[0]?openCase(incoming[0].id):setFilter('法务处理中')},{title:user.role==='courier'?'继续我的处理':'继续我的复核',description:mine.length+' 起案件正在由你负责',icon:<Briefcase24Regular/>,action:()=>mine[0]?openCase(mine[0].id):setFilter('全部案件')}].map(q=><button className="quick-start" key={q.title} onClick={q.action}>{q.icon}<span><strong>{q.title}</strong><small>{q.description}</small></span><ArrowRight24Regular/></button>)}</div>
    <div className="dashboard-metrics">{metrics.map(m=><div className="metric" key={m.label}><div><span>{m.label}</span><span className={'metric-icon ' + (m.tone||'')}>{m.icon}</span></div><strong>{m.value}</strong><small>{m.note}</small></div>)}</div>
    <AiEnginePanel user={user} cases={cases} openCase={openCase}/>
    {incoming.length>0&&<section className="panel incoming-panel"><div className="panel-heading"><h2>{user.role==='courier'?'主管发来的补充要求':'待我接收'} <span className="count">{incoming.length}</span></h2><span>已携带案情、原件和交接说明</span></div>{incoming.slice(0,4).map(c=><div className="incoming-row" key={c.id}><span className="incoming-icon"><PeopleTeam24Regular/></span><div><strong>{c.title}</strong><p>{c.handoffNote||'请核对现有材料后接收案件'}</p><small>{c.ownerName} · {dateText(c.handoffAt||c.updatedAt)}</small></div><Button appearance="primary" onClick={()=>openCase(c.id)}>查看并接收</Button></div>)}</section>}
    {priority && <section className="urgent-banner"><div className="urgent-icon"><Clock24Regular/></div><div className="urgent-copy"><div><span className="urgency-label">优先行动</span><span>{timeLeft(priority.dueAt)}</span></div><h2>{priority.title}</h2><p>{priority.caseTitle} · 截止 {dateText(priority.dueAt)}</p></div><Button appearance="primary" icon={<ArrowRight24Regular/>} iconPosition="after" onClick={()=>openCase(priority.caseId)}>立即处理</Button></section>}
    <div className="dashboard-columns"><section className="panel case-list-panel"><div className="panel-heading"><div><h2>{roleCopy.queue} <span className="count">{cases.length}</span></h2><p>{roleCopy.focus}</p></div><select aria-label="案件排序" value={sort} onChange={e=>setSort(e.target.value)}><option value="risk">风险优先</option><option value="new">最近创建</option></select></div>
      <div className="list-tools"><div className="filter-tabs">{['全部案件','高风险','待补证','法务处理中','已归档'].map(f=><button key={f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="inline-search"><Search24Regular/><input aria-label="搜索案件" placeholder="搜索案件、运单号" value={search} onChange={e=>setSearch(e.target.value)}/></div></div>
      <div className="table-scroll"><table className="case-table"><thead><tr><th>案件 / 运单</th><th>风险等级</th><th>当前阶段</th><th>证据完整度</th><th>下一步行动</th><th></th></tr></thead><tbody>{filtered.map(c=><tr key={c.id} onClick={()=>openCase(c.id)}><td><button className="case-title" onClick={e=>{e.stopPropagation();openCase(c.id);}}>{c.title}</button><small className="mono">{c.waybill}</small></td><td><RiskBadge risk={c.risk}/></td><td><span className={'status ' + (c.status==='已归档'?'status-done':'')}>{c.status}</span></td><td><div className="progress-value"><span>{c.completeness}%</span><small>{c.evidenceCount}/{c.requiredCount}</small></div><div className="progress-track"><i style={{width: Math.min(c.completeness,100) + '%'}}/></div></td><td><span className="next-action">{c.nextAction || '查看案件'}</span><small className={c.dueAt&&Date.parse(c.dueAt)<Date.now()+86400000?'red-text':''}>{c.dueAt?timeLeft(c.dueAt):c.ownerName}</small></td><td><ChevronRight20Regular/></td></tr>)}</tbody></table></div>
      {!filtered.length&&<Empty title="没有符合条件的案件" description="尝试更换筛选条件，或新建一个纠纷案件。"/>}<div className="table-footer"><span>共 {filtered.length} 起案件</span><span>当前身份仅可执行授权操作</span></div>
    </section><aside className="dashboard-aside"><section className="panel todo-panel"><div className="panel-heading"><h2>{user.role==='legal'?'待接收 / 待审核':user.role==='supervisor'?'主管待办':'我的待办'}</h2><span className="count">{urgent.length}</span></div>{urgent.slice(0,4).map(t=><button className="mini-task" key={t.id} onClick={()=>openCase(t.caseId)}><span className={'priority-marker ' + (t.priority==='P0'?'red':'amber')}/><div><strong>{t.title}</strong><small>{t.caseTitle}</small><span className="task-time"><Clock24Regular/>{timeLeft(t.dueAt)}</span></div><ChevronRight20Regular/></button>)}{!urgent.length&&<Empty title="近期没有到期待办" description="关键期限已同步至行动中心。"/>}</section><section className="principle-panel"><div className="principle-icon"><ShieldTask24Regular/></div><h3>{user.role==='legal'?'法务最终决策':user.role==='supervisor'?'主管先审，必要时请求法务':'事发即固证'}</h3><p>{user.role==='courier'?'先固定证据，再描述事实；无法确认时转交主管。':user.role==='supervisor'?'先把网点事实补全，超过权限或判断边界时转交法务。':'只使用可追溯来源，AI 仅辅助整理，结论由法务确认。'}</p><div><CheckmarkCircle24Regular/> 原始文件留存</div><div><CheckmarkCircle24Regular/> 角色协同留痕</div><div><CheckmarkCircle24Regular/> 下一步行动明确</div><small>当前角色：{roleNames[user.role]}</small></section></aside></div>
  </>;
}function TaskPage({ tasks, openCase, refresh, notify }: { tasks: Task[]; openCase: (id: string) => void; refresh: () => Promise<void>; notify: (message: string, error?: boolean) => void }) {
  const [filter, setFilter]=useState('待处理'); const [busy, setBusy]=useState('');
  const mark=async(t:Task)=>{setBusy(t.id);try{await api(`/tasks/${t.id}`,{method:'PATCH',body:JSON.stringify({status:'已完成'})});await refresh();notify('行动已完成，操作已记录');}catch(e){notify((e as Error).message,true);}finally{setBusy('');}};
  const items=tasks.filter(t=>filter==='全部行动'||t.status===filter).sort((a,b)=>Date.parse(a.dueAt)-Date.parse(b.dueAt));
  return <><Heading title="行动中心" description="先保护即将消失的证据，再推进每个处置节点。"/><section className="panel"><div className="panel-heading"><div className="filter-tabs">{['待处理','已完成','全部行动'].map(f=><button key={f} className={f===filter?'active':''} onClick={()=>setFilter(f)}>{f}</button>)}</div><span>{items.length} 项行动</span></div><div className="task-list">{items.map(t=><div className={`task-row ${t.status==='已完成'?'completed':''}`} key={t.id}><span className={`priority-tag ${t.priority==='P0'?'red':'amber'}`}>{t.priority}</span><button className="task-main" onClick={()=>openCase(t.caseId)}><strong>{t.title}</strong><small>{t.caseTitle} · {t.kind}</small></button><div className="task-deadline"><strong>{dateText(t.dueAt)}</strong><small>{t.status==='已完成'?'已完成':timeLeft(t.dueAt)}</small></div>{t.status!=='已完成'&&<Button disabled={busy===t.id} onClick={()=>['legal_review','supervisor_review','evidence'].includes(t.kind)?openCase(t.caseId):mark(t)}>{['legal_review','supervisor_review'].includes(t.kind)?'打开并处理':t.kind==='evidence'?'去上传证据':'标记完成'}</Button>}<Button appearance="subtle" aria-label={`打开${t.caseTitle}`} icon={<ChevronRight20Regular/>} onClick={()=>openCase(t.caseId)}/></div>)}</div>{!items.length&&<Empty title="这里的行动都处理好了" description="新案件的固证任务将自动进入行动中心。"/>}</section></>;
}
function AuditPage() {
  const [logs,setLogs]=useState<AuditLog[]>([]);const [error,setError]=useState('');
  useEffect(()=>{api<{logs:AuditLog[]}>('/audit').then(d=>setLogs(d.logs)).catch(e=>setError(e.message));},[]);
  return <><Heading title="操作审计" description="记录每一次案件变更、证据上传和人工决策。"/>{error&&<div role="alert" className="error-box">{error}</div>}<section className="panel"><div className="panel-heading"><h2>操作记录</h2><span>{logs.length} 条</span></div><div className="audit-list">{logs.map(l=><div className="audit-row" key={l.id}><History24Regular/><div><strong>{l.action}</strong><p>{typeof l.detail==='string'?l.detail:typeof l.details==='string'?l.details:''}</p><small>{l.actorName||l.userName||'系统'}{l.caseId?` · ${l.caseId}`:''}</small></div><time>{dateText(l.createdAt,true)}</time></div>)}</div>{!logs.length&&!error&&<Empty title="暂无审计记录"/>}</section></>;
}
type Page='workbench'|'intake'|'case'|'tasks'|'knowledge'|'audit';
export default function App() {
  const [user,setUser]=useState<User|null>(null);const [boot,setBoot]=useState(true);const [bootError,setBootError]=useState('');
  const [page,setPage]=useState<Page>('workbench');const [cases,setCases]=useState<CaseItem[]>([]);const [tasks,setTasks]=useState<Task[]>([]);
  const [selected,setSelected]=useState('');const [search,setSearch]=useState('');const [toast,setToast]=useState<{text:string;error:boolean}|null>(null);
  const [mobile,setMobile]=useState(false);const [loading,setLoading]=useState(false);
  const notify=useCallback((text:string,error=false)=>setToast({text,error}),[]);
  const refresh=useCallback(async()=>{const [c,t]=await Promise.all([api<{cases:CaseItem[]}>('/cases'),api<{tasks:Task[]}>('/tasks')]);setCases(c.cases);setTasks(t.tasks);},[]);
  useEffect(()=>{api<{user:User}>('/auth/me').then(d=>setUser(d.user)).catch(async()=>{try{await api('/health');}catch{setBootError('无法连接本地服务器，请使用 npm run dev 启动完整应用。');}}).finally(()=>setBoot(false));},[]);
  useEffect(()=>{if(!user)return;setLoading(true);refresh().catch(e=>notify(e.message,true)).finally(()=>setLoading(false));const timer=window.setInterval(()=>refresh().catch(()=>{}),30000);return()=>clearInterval(timer);},[user,refresh,notify]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(null),6000);return()=>clearTimeout(t);},[toast]);
  const go=(p:Page)=>{setPage(p);setMobile(false);};const openCase=(id:string)=>{setSelected(id);go('case');};
  const logout=async()=>{try{await post('/auth/logout');setUser(null);setCases([]);setTasks([]);setSelected('');setPage('workbench');}catch(e){notify((e as Error).message,true);}};
  if(boot)return <div className="boot"><Brand/><Spinner label="连接案件工作台…"/></div>;
  if(!user)return <Login onLogin={setUser} serverError={bootError}/>;
  const nav=[{id:'workbench',label:user.role==='courier'?'我的现场工作台':user.role==='supervisor'?'网点案件指挥台':'法务接收与复核',icon:<Home24Regular/>},...(user.role!=='legal'?[{id:'intake',label:'新建纠纷案件',icon:<Add24Regular/>}]:[]),{id:'tasks',label:user.role==='legal'?'法务复核任务':user.role==='supervisor'?'主管协同任务':'我的固证任务',icon:<TaskListSquareLtr24Regular/>},{id:'knowledge',label:'法律依据与经验库',icon:<BookOpen24Regular/>},...(user.role!=='courier'?[{id:'audit',label:'操作审计',icon:<History24Regular/>}]:[])];
  return <div className="app-shell"><aside className={`sidebar ${mobile?'sidebar-open':''}`}><Brand/><div className="workspace-label">案件管理</div><nav>{nav.map(n=><button key={n.id} onClick={()=>go(n.id as Page)} className={(page===n.id||(page==='case'&&n.id==='workbench'))?'nav-active':''}>{n.icon}<span>{n.label}</span>{n.id==='tasks'&&tasks.some(t=>t.status!=='已完成')&&<b>{tasks.filter(t=>t.status!=='已完成').length}</b>}</button>)}</nav><div className="sidebar-bottom"><div className="competition"><ShieldTask24Regular/><div>2026 顺丰 AI 应用挑战赛<small>事发即固证 · 处置有依据</small></div></div><div className="user-profile"><Avatar name={user.name} size={36} color="neutral"/><div><strong>{user.name}</strong><span>{roleNames[user.role]}</span></div><button title="退出登录 / 切换身份" aria-label="退出登录 / 切换身份" onClick={logout}><ArrowExit20Regular/></button></div></div></aside>{mobile&&<button className="sidebar-scrim" aria-label="关闭菜单" onClick={()=>setMobile(false)}/>}
    <div className="main-shell"><header className="topbar"><div className="breadcrumbs"><button className="mobile-menu" onClick={()=>setMobile(!mobile)} aria-label="打开菜单"><Navigation24Regular/></button><span>纠纷处置</span><ChevronRight20Regular/><strong>{page==='case'?'案件详情':nav.find(n=>n.id===page)?.label}</strong></div><div className="topbar-right"><span className="org-name">{user.org}</span><span className="demo-badge">比赛演示环境</span><button className="notification-button" title="查看期限提醒" onClick={()=>go('tasks')}><Alert24Regular/>{tasks.some(t=>t.status!=='已完成'&&Date.parse(t.dueAt)<Date.now()+86400000)&&<i/>}</button></div></header>
      <main className="main-content" key={page}>{loading&&page==='workbench'?<div className="loading-panel"><Spinner label="读取案件与行动…"/></div>:page==='workbench'?<Workbench user={user} cases={cases} tasks={tasks} openCase={openCase} newCase={()=>go('intake')} search={search} setSearch={setSearch}/>:page==='intake'?<Intake onCreated={async(id)=>{await refresh();openCase(id);}} notify={notify}/>:page==='case'?<CaseWorkspace id={selected} user={user} notify={notify} onChange={refresh} onBack={()=>go('workbench')}/>:page==='tasks'?<TaskPage tasks={tasks} openCase={openCase} refresh={refresh} notify={notify}/>:page==='knowledge'?<KnowledgePage user={user} notify={notify}/>:<AuditPage/>}<footer className="app-footer"><span><ShieldTask24Regular/> 顺丰快递纠纷智能取证与法律处置系统</span><span>AI 辅助研判，处置结论需人工确认</span></footer></main>
    </div>{toast&&<div className={`toast ${toast.error?'toast-error':''}`} role={toast.error?'alert':'status'}>{toast.error?<Alert24Regular/>:<CheckmarkCircle24Regular/>}<span>{toast.text}</span><button aria-label="关闭消息" onClick={()=>setToast(null)}>×</button></div>}
  </div>;
}
