import { useCallback, useEffect, useRef, useState } from 'react';
import { Button, Input, Spinner, Textarea } from '@fluentui/react-components';
import { ArrowDownload24Regular, ArrowLeft24Regular, ArrowRight24Regular, ArrowSync24Regular, ArrowUpload24Regular, CheckmarkCircle24Regular, ChevronRight20Regular, Clock24Regular, DocumentText24Regular, History24Regular, LockClosed24Regular, Scales24Regular, ShieldTask24Regular, Sparkle24Regular } from '@fluentui/react-icons';
import { api, post, dateText, timeLeft } from './api';
import type { CaseItem, Evidence, LegalDocument, User } from './api';
import { Empty, RiskBadge } from './App';

const Scale24Regular = Scales24Regular;

type Notify=(m:string,e?:boolean)=>void;
const labels:Record<string,string>={immediate:'立即固定',supplement:'待补充',available:'已具备'};
const actionNames:Record<string,string>={supplement:'补充证据',negotiate:'记录协商',compensate:'提交赔偿审批',escalate:'申请法务接收',archive:'归档案件',handoff_supervisor:'转交主管审核',accept_supervisor:'接收案件并开始复核',return_courier:'退回快递员补证',request_legal:'申请法务接收',accept_legal:'接收并开始法务审核',return_supervisor:'退回主管补证',legal_approve:'法务审核完成'};
const handoffLabels:Record<string,string>={self_handling:'当前自行处理',awaiting_supervisor:'等待主管接收',supervisor_handling:'主管复核中',returned_to_courier:'主管退回快递员补证',awaiting_legal:'等待法务接收',legal_handling:'法务审核中',returned_to_supervisor:'法务退回主管补证',legal_resolved:'法务已给出处置意见'};

export function CaseWorkspace({id,user,notify,onChange,onBack}:{id:string;user:User;notify:Notify;onChange:()=>Promise<void>;onBack:()=>void}) {
  const [item,setItem]=useState<CaseItem|null>(null);const [error,setError]=useState('');const [tab,setTab]=useState('evidence');const [busy,setBusy]=useState('');
  const [uploadCategory,setUploadCategory]=useState('');const [file,setFile]=useState<File|null>(null);const [fileTitle,setFileTitle]=useState('');const [uploadError,setUploadError]=useState('');
  const [answers,setAnswers]=useState<Record<string,string>>({});const [action,setAction]=useState('');const [note,setNote]=useState('');const [actionError,setActionError]=useState('');
  const [docType,setDocType]=useState('情况说明');const [preview,setPreview]=useState<LegalDocument|null>(null);const [evidencePreview,setEvidencePreview]=useState<Evidence|null>(null);
  const fileInput=useRef<HTMLInputElement>(null);
  const load=useCallback(async()=>{try{const data=await api<{case:CaseItem}>(`/cases/${id}`);setItem(data.case);setAnswers(data.case.clarificationAnswers||{});setError('');}catch(e){setError((e as Error).message);}},[id]);
  useEffect(()=>{load();},[load]);
  const apply=async(data:{case:CaseItem})=>{setItem(data.case);await onChange();};
  const reanalyze=async()=>{setBusy('analysis');try{await apply(await post<{case:CaseItem}>(`/cases/${id}/analysis`,{answers}));notify('研判已更新，引用与分析版本已保存');}catch(e){notify((e as Error).message,true);}finally{setBusy('');}};
  const upload=async(e:React.FormEvent)=>{e.preventDefault();if(!file)return;setBusy('upload');setUploadError('');try{const form=new FormData();form.set('file',file);form.set('title',fileTitle||file.name);form.set('category',uploadCategory);await apply(await api<{case:CaseItem}>(`/cases/${id}/evidence`,{method:'POST',body:form}));setUploadCategory('');setFile(null);setFileTitle('');notify('证据原件已保存，SHA-256 指纹与上传记录已生成');}catch(err){setUploadError((err as Error).message);}finally{setBusy('');}};
  const transition=async(e:React.FormEvent)=>{e.preventDefault();setBusy('action');setActionError('');try{await apply(await post<{case:CaseItem}>(`/cases/${id}/transition`,{action,note}));notify(`${actionNames[action]}已记录`);setAction('');setNote('');}catch(err){setActionError((err as Error).message);}finally{setBusy('');}};
  const document=async()=>{setBusy('document');try{const data=await post<{case:CaseItem}>(`/cases/${id}/documents`,{type:docType});await apply(data);setPreview(data.case.documents.find(d=>d.type===docType)||data.case.documents[0]);notify('文书草稿已生成，请核对事实后使用');}catch(err){notify((err as Error).message,true);}finally{setBusy('');}};
  const verify=async(evidence:Evidence)=>{setBusy(`verify-${evidence.id}`);try{const d=await api<{valid?:boolean;verified?:boolean;matches?:boolean}>(`/evidence/${evidence.id}/verify`);const valid=d.valid??d.verified??d.matches;notify(valid?'文件指纹一致：存储文件自上传后未发生变化':'文件指纹不一致，请联系管理员核查',!valid);}catch(e){notify((e as Error).message,true);}finally{setBusy('');}};
  if(error)return <div className="error-box" role="alert">{error}<Button onClick={load}>重试</Button><Button onClick={onBack}>返回工作台</Button></div>;
  if(!item)return <div className="loading-panel"><Spinner label="正在读取案件证据链…"/></div>;
  const a=item.analysis;const archived=item.status==='已归档';const checklist=a?.checklist||[];const pendingTasks=(item.tasks||[]).filter(t=>t.status!=='已完成');
  const handoffAction = user.role==='courier' ? 'handoff_supervisor' : user.role==='supervisor' ? (item.handoffStatus==='awaiting_supervisor' ? 'accept_supervisor' : 'request_legal') : (item.handoffStatus==='awaiting_legal' ? 'accept_legal' : 'legal_approve');
  const actionList = user.role==='courier'
    ? ['supplement','negotiate',...(item.currentHandlerRole==='courier'||item.handoffStatus==='returned_to_courier'||item.handoffStatus==='self_handling'?['handoff_supervisor']:[])]
    : user.role==='supervisor'
      ? ['supplement','negotiate','compensate',...(item.handoffStatus==='awaiting_supervisor'?['accept_supervisor']:[]),...(item.currentHandlerRole==='supervisor'||item.handoffStatus==='supervisor_handling'||item.handoffStatus==='returned_to_supervisor'?['return_courier','request_legal']:[]),'archive']
      : (item.handoffStatus==='awaiting_legal' ? ['accept_legal'] : ['return_supervisor','legal_approve','archive']);
  const actionExplanation:Record<string,string>={handoff_supervisor:'把本案事实、已上传证据和 AI 固证清单交给网点主管接收；主管会在自己的工作台看到待复核任务。',accept_supervisor:'确认主管已接收案件，接下来由主管补齐网点侧材料并决定是否请求法务。',return_courier:'说明缺少哪一项事实或原始材料，案件会退回原经办快递员并生成补证待办。',request_legal:'把案件、证据、风险信号和主管复核意见发送给法务；法务会在法务工作台接收。',accept_legal:'确认法务接收案件，后续责任、赔偿与法律文书由法务人工复核。',return_supervisor:'记录需要主管补充或重新核验的内容，案件会回到主管工作台。',legal_approve:'记录法务审核意见并回传主管推进协商或赔偿审批。'};
  const startUpload=(category:string,title:string)=>{setUploadCategory(category);setFileTitle(title);setFile(null);setUploadError('');};
  const chooseAction=(value:string)=>{setAction(value);setNote('');setActionError('');};
  return <><button className="back-link" onClick={onBack}><ArrowLeft24Regular/> 返回案件工作台</button><div className="case-heading"><div><div className="case-id"><span>{item.id}</span><span className="status">{item.status}</span>{item.escalated&&<span className="legal-tag"><Scale24Regular/> 法务已介入</span>}</div><h1>{item.title}</h1><div className="case-heading-meta"><span className="mono">{item.waybill}</span><i/><span>{item.category}纠纷</span><i/><span>负责人：{item.ownerName}</span><i/><span>{dateText(item.createdAt)} 创建</span></div></div><div className="heading-actions"><Button icon={<ArrowSync24Regular/>} onClick={reanalyze} disabled={!!busy||archived}>{busy==='analysis'?'正在重新研判…':'重新研判'}</Button>{!archived&&user.role==='courier'&&(item.currentHandlerRole==='courier'||item.handoffStatus==='returned_to_courier'||item.handoffStatus==='self_handling')&&<Button appearance="primary" onClick={()=>chooseAction(handoffAction)} icon={<Scale24Regular/>}>{actionNames[handoffAction]}</Button>}{!archived&&user.role==='supervisor'&&!item.escalated&&<Button appearance="primary" onClick={()=>chooseAction(handoffAction)} icon={<Scale24Regular/>}>{actionNames[handoffAction]}</Button>}{!archived&&user.role==='legal'&&item.handoffStatus==='awaiting_legal'&&<Button appearance="primary" onClick={()=>chooseAction('accept_legal')} icon={<Scale24Regular/>}>接收案件</Button>}</div></div>
    <div className={'handoff-banner handoff-' + (item.handoffStatus||'self_handling')}><span className="handoff-dot"/><div><strong>{handoffLabels[item.handoffStatus||'self_handling']||'当前处理环节'}</strong><span>{item.currentHandlerName?('当前处理人：'+item.currentHandlerName):'当前处理人待确认'}{item.handoffNote?' · '+item.handoffNote:''}</span></div><div className="handoff-chain"><b className={item.currentHandlerRole==='courier'?'on':''}>快递员</b><ArrowRight24Regular/><b className={item.currentHandlerRole==='supervisor'?'on':''}>主管</b><ArrowRight24Regular/><b className={item.currentHandlerRole==='legal'?'on':''}>法务</b></div></div>
    <div className="case-summary-strip"><div><span>责任风险辅助研判</span><RiskBadge risk={item.risk}/></div><div><span>客户主张金额</span><strong>¥ {Number(item.amount).toLocaleString('zh-CN',{minimumFractionDigits:2})}</strong></div><div><span>证据完整度</span><strong>{item.completeness}<small>%</small><em>{item.evidenceCount} / {item.requiredCount} 类已上传</em></strong></div><div><span>当前优先行动</span><strong className="summary-next">{item.nextAction||'查看处置建议'}</strong></div></div>
    {a?.escalationReasons?.length>0&&!archived&&<div className="legal-notice"><Scale24Regular/><div><strong>已触发人工法务复核</strong><span>{a.escalationReasons.join('；')}。固证工作可继续推进，责任与赔付结论由授权人员确认。</span></div></div>}
    <div className="case-tabs" role="tablist" aria-label="案件详情页签">{[{id:'evidence',label:'AI 固证清单',icon:<ShieldTask24Regular/>},{id:'risk',label:'案情与责任研判',icon:<Scale24Regular/>},{id:'action',label:'处置 SOP',icon:<ArrowRight24Regular/>},{id:'documents',label:'法律文书',icon:<DocumentText24Regular/>},{id:'timeline',label:'案件时间线',icon:<History24Regular/>}].map(t=><button role="tab" aria-selected={tab===t.id} key={t.id} className={tab===t.id?'active':''} onClick={()=>setTab(t.id)}>{t.icon}{t.label}{t.id==='evidence'&&<span>{checklist.length}</span>}</button>)}</div>
    <div className="case-content-layout"><div className="case-primary">
    {tab==='evidence'&&<><section className="panel"><div className="panel-heading"><div><h2><Sparkle24Regular/> 固证行动清单</h2><p>优先保留易灭失证据，再逐项补全证据链</p></div><span className="mode-badge">{a?.mode==='llm'?'AI 检索增强模式':'规则辅助模式'}</span></div><div className="evidence-groups">{(['immediate','supplement','available'] as const).map(group=>{const rows=checklist.filter(c=>c.priority===group);return <div className={`evidence-group group-${group}`} key={group}><h3><span className="group-dot"/>{labels[group]}<span className="count">{rows.length}</span>{group==='immediate'&&<small>时间敏感，优先处理</small>}</h3>{rows.map(c=><div className="checklist-row" key={c.id}><span className={`checklist-icon ${group==='available'?'checked':''}`}>{group==='available'?<CheckmarkCircle24Regular/>:<DocumentText24Regular/>}</span><div><strong>{c.title}</strong><p>{c.reason}</p>{c.deadlineHours&&group!=='available'?<small className="red-text">建议 {c.deadlineHours} 小时内落实，实际期限需核验</small>:null}</div>{group==='available'?<span className="evidence-saved"><LockClosed24Regular/> 已留存</span>:<Button disabled={archived} onClick={()=>startUpload(c.category,c.title)} icon={<ArrowUpload24Regular/>}>上传证据</Button>}</div>)}{!rows.length&&<div className="group-empty">{group==='available'?'上传对应原件后，清单会自动更新。':`暂无${labels[group]}的项目`}</div>}</div>;})}</div></section><section className="panel evidence-files"><div className="panel-heading"><div><h2>已上传原始文件 <span className="count">{item.evidence.length}</span></h2><p>指纹用于检测文件变化，不等同于真实性或司法效力认证</p></div></div>{item.evidence.map(e=><div className="file-row" key={e.id}><span className="file-icon"><DocumentText24Regular/></span><button className="file-info" onClick={()=>setEvidencePreview(e)}><strong>{e.title}</strong><small>{e.originalName} · {(e.size/1024).toFixed(1)} KB · {dateText(e.createdAt)}</small><code>SHA-256 {e.sha256.slice(0,20)}…</code></button><Button appearance="subtle" onClick={()=>verify(e)} disabled={busy===`verify-${e.id}`}>校验</Button><a href={`/api/evidence/${e.id}/download`} className="icon-link" title={`下载${e.title}`}><ArrowDownload24Regular/></a></div>)}{!item.evidence.length&&<Empty title="还没有上传证据" description="从上方固证清单选择对应项目，上传原始文件。"/>}</section></>}
    {tab==='risk'&&<><section className="panel facts-panel"><div className="panel-heading"><h2>已知案情</h2><span className="source-label">来源：报案人陈述</span></div><p className="case-description">{item.description}</p><div className="fact-grid"><div><span>货物</span><strong>{item.goods}</strong></div><div><span>保价信息</span><strong>{item.insured?'已保价，待核验凭证':'未填报保价'}</strong></div><div><span>事发时间</span><strong>{dateText(item.incidentAt,true)}</strong></div><div><span>风险信号</span><strong>{[item.major?'重大案件':'',item.criminalRisk?'刑事风险':''].filter(Boolean).join('、')||'暂无手动标记'}</strong></div></div></section><section className="panel risk-panel"><div className="panel-heading"><h2>责任风险辅助研判</h2><RiskBadge risk={item.risk}/></div><p className="analysis-summary">{a?.summary}</p><div className="focus-points">{a?.focusPoints?.map((p,i)=><div key={i}><span>{String(i+1).padStart(2,'0')}</span><p>{p}</p></div>)}</div>{a?.riskReasons?.map((r,i)=><p className="risk-reason" key={i}>{r}</p>)}<div className="analysis-disclaimer">{a?.disclaimer||'AI 仅辅助梳理风险，不作责任认定或赔偿承诺。'}</div></section><section className="panel clarification-panel"><div className="panel-heading"><div><h2>还需要澄清的问题</h2><p>回答后重新研判，保留每次分析记录</p></div></div><div className="clarification-fields">{a?.questions?.map((q,i)=><label className="field" key={q.id}><span><b className="question-number">{i+1}</b>{q.question}</span><Textarea rows={2} resize="vertical" disabled={archived} value={answers[q.id]||''} onChange={(_,d)=>setAnswers(v=>({...v,[q.id]:d.value}))} placeholder="填写已核实信息；尚不清楚可注明待核验"/></label>)}<Button appearance="primary" disabled={!!busy||archived} onClick={reanalyze}>{busy==='analysis'?'保存并研判中…':'保存澄清并更新研判'}</Button></div></section><section className="panel citations-panel"><div className="panel-heading"><div><h2>本次检索依据</h2><p>来源与版本随本次研判留存</p></div><span className="mode-badge">{a?.mode==='llm'?'AI 检索增强':'本地知识检索'}</span></div>{a?.citations?.map((c,i)=><div className="citation" key={c.id}><span className="citation-index">{i+1}</span><div><strong>{c.title}</strong><p>{c.excerpt}</p><small>{c.version}</small>{/^https?:\/\//.test(c.sourceUrl)&&<a href={c.sourceUrl} target="_blank" rel="noreferrer">核验原始来源 <ChevronRight20Regular/></a>}</div></div>)}{!a?.citations?.length&&<Empty title="未检索到相关依据" description="请法务补充可核验来源，不据此推断法律结论。"/>}</section></>}
    {tab==='action'&&<><section className="panel"><div className="panel-heading"><div><h2>建议处置路径</h2><p>按已知事实推进，每次决定均记录理由；需要协同时，用角色转交动作把案件发到下一工作台。</p></div></div><div className="sop-list">{a?.sop?.map((s,i)=><div className="sop-step" key={i}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{s.title}</h3><p>{s.description}</p></div></div>)}</div><div className="action-buttons">{actionList.map(act=><Button key={act} disabled={archived||(act==='request_legal'&&item.escalated)} onClick={()=>chooseAction(act)} appearance={act.includes('handoff')||act.includes('request')||act.includes('accept')||act.includes('approve')?'primary':act==='negotiate'?'primary':'secondary'}>{actionNames[act]}</Button>)}</div>{user.role==='courier'&&<p className="permission-note">你可以先完成固证与协商；无法确认责任或协商卡住时，再转交主管。赔偿审批和归档由主管 / 法务操作。</p>}{user.role==='supervisor'&&<p className="permission-note">主管通常先闭环；高金额、重大、刑事风险或判断边界不清时，申请法务接收。</p>}{user.role==='legal'&&<p className="permission-note">法务接收后可退回补证，或完成审核并把处置意见回传主管。法律结论由人工确认。</p>}</section><section className="panel"><div className="panel-heading"><h2>本案行动</h2><span>{pendingTasks.length} 项待处理</span></div>{item.tasks.map(t=><div className="case-task" key={t.id}><span className={`task-state-icon ${t.status==='已完成'?'green-text':''}`}>{t.status==='已完成'?<CheckmarkCircle24Regular/>:<Clock24Regular/>}</span><div><strong>{t.title}</strong><small>{dateText(t.dueAt)} · {t.priority} · {t.status}</small></div>{t.status!=='已完成'&&!archived&&<Button onClick={async()=>{setBusy(t.id);try{await api(`/tasks/${t.id}`,{method:'PATCH',body:JSON.stringify({status:'已完成',note:'已在工作台完成本项行动'})});await load();await onChange();notify('行动已完成');}catch(e){notify((e as Error).message,true);}finally{setBusy('');}}} disabled={!!busy}>标记完成</Button>}</div>)}</section></>}
    {tab==='documents'&&<><section className="panel document-generator"><div className="panel-heading"><div><h2>生成法律文书草稿</h2><p>基于本案事实与已上传证据生成，未知事项保留待核验标记</p></div></div><div className="document-types">{['情况说明','证据目录','监控调取函',...(user.role==='legal'?['答辩材料']:[])].map(t=><button className={docType===t?'selected':''} key={t} onClick={()=>setDocType(t)}><DocumentText24Regular/><strong>{t}</strong><span>{t==='情况说明'?'整理已知经过':t==='证据目录'?'汇总原件与文件指纹':t==='监控调取函'?'申请留存关键监控':'法务复核专用草稿'}</span></button>)}</div><div className="form-footer"><span>所有文书均为待人工审阅草稿</span><Button appearance="primary" onClick={document} disabled={!!busy||archived} icon={<Sparkle24Regular/>}>{busy==='document'?'正在生成…':'生成文书草稿'}</Button></div></section><section className="panel"><div className="panel-heading"><h2>本案文书 <span className="count">{item.documents.length}</span></h2></div>{item.documents.map(d=><div className="file-row" key={d.id}><span className="file-icon"><DocumentText24Regular/></span><button className="file-info" onClick={()=>setPreview(d)}><strong>{d.title||d.type}</strong><small>{dateText(d.createdAt)} · {d.status||'待法务审阅'}</small></button><Button onClick={()=>setPreview(d)}>预览</Button><a href={`/api/documents/${d.id}/download`} className="icon-link" title="下载文书"><ArrowDownload24Regular/></a></div>)}{!item.documents.length&&<Empty title="还没有生成文书" description="选择文书类型，生成可下载的初稿。"/>}</section></>}
    {tab==='timeline'&&<section className="panel"><div className="panel-heading"><div><h2>案件时间线</h2><p>从第一份报告到最终归档，关键操作有迹可查</p></div><span className="count">{item.timeline.length}</span></div><div className="timeline">{item.timeline.map((t,i)=><div className="timeline-entry" key={t.id}><div className={`timeline-dot ${i===0?'latest':''}`}><History24Regular/></div><div><div className="timeline-title"><h3>{t.action}</h3><time>{dateText(t.createdAt,true)}</time></div><p>{t.detail||t.details||''}</p><span>{t.actorName||t.userName||'系统'}</span></div></div>)}</div></section>}
    </div><aside className="case-aside"><section className="panel next-step-panel"><span className="aside-eyebrow">NEXT ACTION</span><h2>下一步做什么</h2><div className="next-step-icon"><ShieldTask24Regular/></div><h3>{archived?'案件已归档':item.nextAction||'核对并补齐证据'}</h3><p>{archived?'原始证据、文书和操作记录已留存，可继续查阅与下载。':'从当前缺失的证据开始，避免因等待责任结论错过保全时机。'}</p>{!archived&&<Button appearance="primary" icon={<ArrowRight24Regular/>} iconPosition="after" onClick={()=>{const c=checklist.find(c=>c.priority==='immediate')||checklist.find(c=>c.priority==='supplement');if(c){setTab('evidence');startUpload(c.category,c.title);}else setTab('action');}}>开始处理</Button>}</section><section className="panel deadlines-panel"><div className="panel-heading"><h2><Clock24Regular/> 关键期限</h2></div>{[{label:'监控覆盖',date:item.monitorDeadline},{label:'保险报案',date:item.insuranceDeadline},{label:'举证截止',date:item.proofDeadline}].map(d=><div className="deadline-item" key={d.label}><span>{d.label}</span><strong className={d.date&&Date.parse(d.date)<Date.now()+86400000?'red-text':''}>{d.date?timeLeft(d.date):'待核验'}</strong><small>{d.date?dateText(d.date):'以实际保管规则或通知为准'}</small></div>)}</section><div className="case-ai-note"><Sparkle24Regular/><p><strong>{a?.mode==='llm'?'检索增强生成已启用':'当前为规则辅助模式'}</strong><span>{a?.mode==='llm'?'模型根据已检索知识辅助整理案情，风险升级由规则约束。':'本地分类与知识检索可用，配置服务端模型后可启用 AI 增强。'}</span><span>上传文件已保全，内容真实性、图像和视频细节仍需人工核验。</span></p></div></aside></div>
    {uploadCategory&&<div className="modal-backdrop"><section role="dialog" aria-modal="true" aria-label="上传证据原件" className="modal"><div className="modal-header"><div><h2>上传证据原件</h2><p>{checklist.find(c=>c.category===uploadCategory)?.title}</p></div><Button onClick={()=>!busy&&setUploadCategory('')} disabled={!!busy}>取消</Button></div><form onSubmit={upload}><label className="field"><span>证据名称</span><Input autoFocus required value={fileTitle} onChange={(_,d)=>setFileTitle(d.value)} maxLength={200}/></label><input ref={fileInput} className="hidden-input" type="file" accept="image/*,video/mp4,video/quicktime,video/webm,.pdf,.txt,.csv,.docx,.xlsx,.eml" onChange={e=>setFile(e.target.files?.[0]||null)}/><button type="button" className="upload-zone" onClick={()=>fileInput.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();setFile(e.dataTransfer.files[0]||null);}}><ArrowUpload24Regular/><strong>{file?file.name:'点击选择，或拖拽原始文件到这里'}</strong><span>{file?`${(file.size/1024/1024).toFixed(2)} MB · 点击重新选择`:'图片、视频、聊天记录、运单及文档，单文件不超过 50 MB'}</span></button><div className="upload-note"><LockClosed24Regular/><p>系统保留原文件、上传时间和 SHA-256 指纹。请勿用修改后的截图替代原始记录。</p></div>{uploadError&&<div className="error-box" role="alert">{uploadError}</div>}<div className="form-footer"><span>上传后自动更新固证清单</span><Button type="submit" appearance="primary" disabled={!file||!!busy}>{busy==='upload'?'上传并保存中…':'保存证据原件'}</Button></div></form></section></div>}
    {action&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label={actionNames[action]}><div className="modal-header"><h2>{actionNames[action]}</h2><Button onClick={()=>setAction('')} disabled={!!busy}>取消</Button></div><p className="action-explanation">{actionExplanation[action]|| (action==='archive'?'归档前须完成全部待办并记录最终处置结果；法务案件由法务归档。':action==='compensate'?'记录拟赔付方案及核验依据，进入审批阶段。此操作不会支付款项。':action==='escalate'?'将案件、现有证据与升级原因一并交由人工法务处理。':'记录本次处理内容、客户反馈与后续安排。')}</p><form onSubmit={transition}><label className="field"><span>处置说明 / 决策依据</span><Textarea autoFocus required minLength={4} rows={5} maxLength={5000} value={note} onChange={(_,d)=>setNote(d.value)} placeholder="请记录具体事实、处理意见与后续安排（至少 4 字）"/></label>{actionError&&<div className="error-box" role="alert">{actionError}</div>}<div className="form-footer"><span>本次操作将写入案件时间线</span><Button type="submit" appearance="primary" disabled={!!busy}>{busy==='action'?'正在保存…':'确认并记录'}</Button></div></form></section></div>}
    {preview&&<div className="modal-backdrop"><section role="dialog" aria-modal="true" aria-label="文书预览" className="modal document-preview"><div className="modal-header"><div><h2>{preview.title||preview.type}</h2><span className="draft-tag">草稿 · 待人工审阅</span></div><Button onClick={()=>setPreview(null)}>关闭</Button></div><pre>{preview.content}</pre><div className="form-footer"><span>请核对事实、当事人和提交要求</span><a className="download-button" href={`/api/documents/${preview.id}/download`}><ArrowDownload24Regular/> 下载文书 .txt</a></div></section></div>}
    {evidencePreview&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="证据详情"><div className="modal-header"><h2>{evidencePreview.title}</h2><Button onClick={()=>setEvidencePreview(null)}>关闭</Button></div><div className="evidence-details"><p><strong>原始文件：</strong>{evidencePreview.originalName}</p><p><strong>上传时间：</strong>{dateText(evidencePreview.createdAt,true)}</p><p><strong>文件大小：</strong>{evidencePreview.size.toLocaleString()} 字节</p><p><strong>SHA-256 文件指纹</strong></p><code>{evidencePreview.sha256}</code><p className="muted">通过下载查看完整原件。指纹一致仅表明存储文件未变更，不认证来源和内容真实性。</p></div><div className="form-footer"><Button onClick={()=>verify(evidencePreview)}>校验原件完整性</Button><a className="download-button" href={`/api/evidence/${evidencePreview.id}/download`}><ArrowDownload24Regular/> 下载原件</a></div></section></div>}
  </>;
}
