import { useEffect, useState } from 'react';
import { Button, Checkbox, Input, Spinner, Textarea } from '@fluentui/react-components';
import { Add24Regular, ArrowRight24Regular, ArrowUpload24Regular, BookOpen24Regular, Box24Regular, CheckmarkCircle24Regular, DocumentText24Regular, LockClosed24Regular, PeopleTeam24Regular, Person24Regular, Scales24Regular, Search24Regular, ShieldTask24Regular } from '@fluentui/react-icons';
import { api, post, roleNames } from './api';
import type { CaseItem, Knowledge, Role, User } from './api';
import { Brand, Empty, Heading } from './App';

const Scale24Regular = Scales24Regular;

export function Login({ onLogin, serverError }: { onLogin: (u: User) => void; serverError: string }) {
  const [role,setRole]=useState<Role>('supervisor');const [username,setUsername]=useState('supervisor');const [password,setPassword]=useState('Sf2026!demo');const [error,setError]=useState(serverError);const [busy,setBusy]=useState(false);
  const login=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const d=await post<{user:User}>('/auth/login',{username,password,role});onLogin(d.user);}catch(err){setError((err as Error).message);}finally{setBusy(false);}};
  return <div className="login-page"><header><Brand/><span className="login-competition">2026 顺丰 AI 应用挑战赛</span></header><main className="login-layout"><section className="login-story"><span className="intro-label"><ShieldTask24Regular/> 让每一次处置，都有据可依</span><h1>事发即固证。<br/><span>把主动权留在现场。</span></h1><p>从纠纷发生的第一刻，明确要留什么证据、<br className="desktop-break"/>风险在哪里，以及下一步该做什么。</p><div className="story-flow">{[{icon:<Box24Regular/>,title:'发现纠纷',sub:'一线快速建案'},{icon:<ShieldTask24Regular/>,title:'立即固证',sub:'留住关键证据'},{icon:<Scale24Regular/>,title:'有据处置',sub:'协同法务决策'}].map((s,i)=><div key={s.title}><span className="story-icon">{s.icon}</span><strong>{s.title}</strong><small>{s.sub}</small>{i<2&&<ArrowRight24Regular className="story-arrow"/>}</div>)}</div><div className="story-note"><span/> 全流程留痕 <i/> 三角色协同 <i/> 法律来源可追溯</div></section>
      <section className="login-card"><div className="login-card-heading"><h2>登录工作台</h2><p>选择工作身份，开始处理案件</p></div><div className="role-selector" aria-label="选择登录身份">{([{id:'courier',icon:<Person24Regular/>},{id:'supervisor',icon:<PeopleTeam24Regular/>},{id:'legal',icon:<Scale24Regular/>}] as const).map(r=><button key={r.id} aria-pressed={role===r.id} onClick={()=>{setRole(r.id);setUsername(r.id);}} className={role===r.id?'selected':''}>{r.icon}<strong>{roleNames[r.id]}</strong>{role===r.id&&<CheckmarkCircle24Regular className="selected-check"/>}</button>)}</div><form onSubmit={login}><label className="field"><span>员工账号</span><Input required autoComplete="username" value={username} onChange={(_,d)=>setUsername(d.value)} placeholder="请输入员工账号" contentBefore={<Person24Regular/>}/></label><label className="field"><span>登录密码</span><Input required type="password" autoComplete="current-password" value={password} onChange={(_,d)=>setPassword(d.value)} contentBefore={<LockClosed24Regular/>}/></label>{error&&<div role="alert" className="error-box">{error}</div>}<Button className="login-submit" appearance="primary" size="large" type="submit" disabled={busy} icon={busy?<Spinner size="tiny"/>:<ArrowRight24Regular/>} iconPosition="after">{busy?'正在验证身份…':'进入工作台'}</Button></form><div className="demo-login-note"><strong>比赛演示账号已填入</strong><span>三种身份独立鉴权，可退出后切换体验。</span><code>统一密码：Sf2026!demo</code></div><p className="login-permission"><LockClosed24Regular/> 服务端校验身份，仅展示授权案件</p></section></main><footer><span>顺丰快递纠纷智能取证与法律处置系统</span><span>AI 辅助研判 · 法务最终决策</span></footer></div>;
}

const localTime=(date:Date)=>new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);
export function Intake({ onCreated, notify }: { onCreated: (id:string)=>Promise<void>; notify:(m:string,e?:boolean)=>void }) {
  const [title,setTitle]=useState('');const [waybill,setWaybill]=useState('');const [goods,setGoods]=useState('');const [amount,setAmount]=useState('');const [description,setDescription]=useState('');
  const [incidentAt,setIncidentAt]=useState(localTime(new Date()));const [monitorDeadline,setMonitorDeadline]=useState('');const [insuranceDeadline,setInsuranceDeadline]=useState('');const [proofDeadline,setProofDeadline]=useState('');
  const [insured,setInsured]=useState(false);const [major,setMajor]=useState(false);const [criminalRisk,setCriminal]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const demo=()=>{setTitle('相机运输破损争议');setWaybill(`SF${Date.now()}`);setGoods('相机及镜头');setAmount('12800');setDescription('客户反馈相机签收后发现镜头破损，外箱一角挤压变形，要求赔偿 12800 元。寄件时包装情况需核验，客户暂未提供购买凭证。分拨中心监控预计 6 小时后覆盖，需立即调取。');setMonitorDeadline(localTime(new Date(Date.now()+6*3600000)));setInsured(false);};
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const data=await post<{case:CaseItem}>('/cases',{title,waybill,goods,amount:Number(amount),description,insured,major,criminalRisk,incidentAt:new Date(incidentAt).toISOString(),...(monitorDeadline?{monitorDeadline:new Date(monitorDeadline).toISOString()}:{}),...(insuranceDeadline?{insuranceDeadline:new Date(insuranceDeadline).toISOString()}:{}),...(proofDeadline?{proofDeadline:new Date(proofDeadline).toISOString()}:{})});notify('案件已建立，固证清单和处置任务已生成');await onCreated(data.case.id);}catch(err){setError((err as Error).message);}finally{setBusy(false);}};
  return <><Heading title="新建纠纷案件" description="先记录已知事实。暂不确定的信息，可在澄清环节继续补充。" actions={<Button onClick={demo} icon={<DocumentText24Regular/>}>填入演示案情</Button>}/><div className="intake-layout"><form className="panel intake-form" onSubmit={submit}><div className="form-section"><div className="section-title"><span>01</span><h2>运单与基本信息</h2></div><div className="form-grid"><label className="field span-2"><span>案件名称 <b>*</b></span><Input required maxLength={100} value={title} onChange={(_,d)=>setTitle(d.value)} placeholder="例如：深圳相机运输破损争议"/></label><label className="field"><span>运单号 <b>*</b></span><Input required maxLength={40} value={waybill} onChange={(_,d)=>setWaybill(d.value)} placeholder="SF 开头的运单号"/></label><label className="field"><span>货物名称 <b>*</b></span><Input required maxLength={100} value={goods} onChange={(_,d)=>setGoods(d.value)} placeholder="例如：相机及镜头"/></label><label className="field"><span>争议金额（元）<b>*</b></span><Input required type="number" min={0} max={100000000} step="0.01" value={amount} onChange={(_,d)=>setAmount(d.value)} placeholder="客户主张金额，不代表确认损失"/></label><label className="field"><span>事发时间 <b>*</b></span><input required type="datetime-local" value={incidentAt} onChange={e=>setIncidentAt(e.target.value)}/></label></div><Checkbox label="已购买保价服务（仍需核验条款及凭证）" checked={insured} onChange={(_,d)=>setInsured(d.checked===true)}/></div>
      <div className="form-section"><div className="section-title"><span>02</span><h2>描述发生了什么</h2></div><label className="field"><span>案情描述 <b>*</b></span><Textarea required minLength={10} maxLength={10000} rows={5} resize="vertical" value={description} onChange={(_,d)=>setDescription(d.value)} placeholder="记录货物状况、寄收件经过、客户诉求、已知证据与紧急情况。请区分亲历事实和客户陈述。"/><small>请勿录入与本案无关的身份证号、银行卡号等敏感信息。</small></label><div className="checkbox-row"><Checkbox label="重大案件 / 群体投诉" checked={major} onChange={(_,d)=>setMajor(d.checked===true)}/><Checkbox label="涉嫌盗窃、诈骗等刑事风险" checked={criminalRisk} onChange={(_,d)=>setCriminal(d.checked===true)}/></div></div>
      <div className="form-section"><div className="section-title"><span>03</span><h2>关键期限 <small>可选，须以实际通知为准</small></h2></div><div className="form-grid"><label className="field"><span>监控预计覆盖时间</span><input type="datetime-local" value={monitorDeadline} onChange={e=>setMonitorDeadline(e.target.value)}/></label><label className="field"><span>保险报案截止时间</span><input type="datetime-local" value={insuranceDeadline} onChange={e=>setInsuranceDeadline(e.target.value)}/></label><label className="field span-2"><span>举证截止时间</span><input type="datetime-local" value={proofDeadline} onChange={e=>setProofDeadline(e.target.value)}/></label></div><p className="muted form-note">未提供具体期限时，系统只生成核验提醒，不推算法律期限。</p></div>{error&&<div role="alert" className="error-box">{error}</div>}<div className="form-footer"><span>提交后自动分类、生成固证清单</span><Button type="submit" appearance="primary" size="large" disabled={busy} icon={busy?<Spinner size="tiny"/>:<ArrowRight24Regular/>} iconPosition="after">{busy?'正在建案并分析…':'建立案件并生成清单'}</Button></div></form>
      <aside className="intake-guide"><div className="panel"><div className="guide-symbol"><ShieldTask24Regular/></div><h3>先把证据留住</h3><p>即使责任尚不明确，也可以立即开始证据保全。</p><ol><li><strong>记录原始状态</strong><span>包装、货物、运单同框拍摄，避免二次破坏。</span></li><li><strong>保留原始文件</strong><span>上传原图、完整聊天和原始视频，保留来源与时间。</span></li><li><strong>核实覆盖期限</strong><span>联系监控保管人，确认时间段并申请留存。</span></li></ol></div><div className="small-notice"><Scale24Regular/><p>高金额、重大及刑事风险案件自动进入法务处理。金额阈值为本次 MVP 演示配置。</p></div></aside></div></>;
}

export function KnowledgePage({user,notify}:{user:User;notify:(m:string,e?:boolean)=>void}) {
  const [query,setQuery]=useState('');const [type,setType]=useState('全部');const [items,setItems]=useState<Knowledge[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [showAdd,setShowAdd]=useState(false);const [selected,setSelected]=useState<Knowledge|null>(null);
  const [newTitle,setNewTitle]=useState('');const [newType,setNewType]=useState(user.role==='legal'?'内部SOP':'历史案例');const [content,setContent]=useState('');const [url,setUrl]=useState('');const [version,setVersion]=useState('经验提交 · '+new Date().toISOString().slice(0,10));const [file,setFile]=useState<File|null>(null);const [saving,setSaving]=useState(false);const [reviewing,setReviewing]=useState('');const [revision,setRevision]=useState(0);
  useEffect(()=>{const controller=new AbortController();const timer=setTimeout(()=>{setLoading(true);api<{items:Knowledge[]}>('/knowledge?q='+encodeURIComponent(query)+'&type='+encodeURIComponent(type==='全部'?'':type),{signal:controller.signal}).then(d=>{setItems(d.items);setError('');}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});},200);return()=>{clearTimeout(timer);controller.abort();};},[query,type,revision]);
  const resetForm=()=>{setNewTitle('');setContent('');setUrl('');setFile(null);setVersion('经验提交 · '+new Date().toISOString().slice(0,10));setNewType(user.role==='legal'?'内部SOP':'历史案例');};
  const openCreate=()=>{resetForm();setShowAdd(true);};
  const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);try{let finalContent=content.trim();if(file&&!finalContent&&(file.type.startsWith('text/')||/\.(txt|md|csv)$/i.test(file.name))){try{finalContent=await file.text();}catch{finalContent='附件已上传，正文请以原始文件为准。';}}if(file){const form=new FormData();form.set('title',newTitle);form.set('type',newType);form.set('content',finalContent);form.set('sourceUrl',url);form.set('version',version);form.set('file',file);await api('/knowledge/upload',{method:'POST',body:form});}else await post('/knowledge',{title:newTitle,type:newType,content:finalContent,sourceUrl:url,version});setShowAdd(false);resetForm();setRevision(n=>n+1);notify(newType==='历史案例'?'经验案例已提交，等待法务审核后参与正式检索':'知识条目已入库，可立即检索');}catch(err){notify((err as Error).message,true);}finally{setSaving(false);}};
  const review=async(item:Knowledge,status:'已审核'|'已退回')=>{setReviewing(item.id);try{await api('/knowledge/'+item.id+'/review',{method:'PATCH',body:JSON.stringify({status,note:status==='已审核'?'已核验来源、事实范围和可引用边界。':'请补充可核验来源、原始材料或事实时间线。'})});setRevision(n=>n+1);notify(status==='已审核'?'经验案例已审核，可参与后续检索':'经验案例已退回，暂不参与检索');}catch(err){notify((err as Error).message,true);}finally{setReviewing('');}};
  return <><Heading title="法律依据与经验库" description="法律来源必须可追溯；一线经验可以提交，经过法务审核后再进入正式引用。" actions={<Button appearance="primary" icon={<Add24Regular/>} onClick={openCreate}>提交知识 / 经验案例</Button>}/><div className="knowledge-role-note"><ShieldTask24Regular/><div><strong>{user.role==='courier'?'快递员：提交现场经验和处置记录':user.role==='supervisor'?'主管：沉淀网点 SOP 与历史处置经验':'法务：审核经验案例并维护可引用法律依据'}</strong><span>提交内容会记录创建人和时间；历史案例不会自动成为法律结论或胜诉依据。</span></div></div><div className="knowledge-search panel"><Search24Regular/><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="搜索知识库" placeholder="搜索争议问题、法律法规或处置方法，例如：货物破损赔偿"/><span>检索增强知识库</span></div><div className="knowledge-filters filter-tabs">{['全部','法律法规','行业规则','内部SOP','历史案例','文书模板'].map(t=><button key={t} className={t===type?'active':''} onClick={()=>setType(t)}>{t}</button>)}</div>{error&&<div role="alert" className="error-box">{error}</div>}{loading?<div className="loading-panel"><Spinner label="正在检索知识库…"/></div>:<div className="knowledge-grid">{items.map(k=><article className="panel knowledge-card" key={k.id}><div className="knowledge-card-meta"><span className="knowledge-icon"><BookOpen24Regular/></span><span className="knowledge-type">{k.type}</span>{k.reviewStatus&&<span className="review-badge">{k.reviewStatus}</span>}{k.isDemo?<span className="demo-badge">演示内容</span>:null}</div><h2>{k.title}</h2><p>{k.content}</p><div className="knowledge-card-bottom"><span>{k.version||'待复核版本'}{k.createdByName?' · '+k.createdByName:''}</span><Button appearance="subtle" icon={<ArrowRight24Regular/>} iconPosition="after" onClick={()=>setSelected(k)}>阅读原文</Button></div>{user.role==='legal'&&k.reviewStatus==='待法务审核'&&<div className="knowledge-review-actions"><span>经验案例待复核</span><Button size="small" appearance="primary" disabled={reviewing===k.id} onClick={()=>review(k,'已审核')}>通过并纳入检索</Button><Button size="small" disabled={reviewing===k.id} onClick={()=>review(k,'已退回')}>退回</Button></div>}</article>)}</div>}{!loading&&!items.length&&<Empty title="未检索到相关依据" description="尝试更具体的关键词；系统不会补造法律依据。"/>}
    {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section role="dialog" aria-modal="true" aria-label="知识详情" className="modal knowledge-modal" onClick={e=>e.stopPropagation()}><div className="modal-header"><span>{selected.type} · {selected.version}</span><Button onClick={()=>setSelected(null)}>关闭</Button></div><h2>{selected.title}</h2><div className="knowledge-content">{selected.content}</div><p className="muted">{selected.reviewStatus?('审核状态：'+selected.reviewStatus+'。'):''}{selected.isDemo?' 本条为比赛演示材料，非顺丰正式制度或真实裁判案例。':(' 核验日期：'+(selected.verifiedAt||'请人工核验'))}</p>{selected.attachmentName&&<div className="knowledge-attachment"><span>附件：{selected.attachmentName}</span>{import.meta.env.MODE==='github-pages'?<small>静态演示仅展示附件元数据</small>:<a href={'/api/knowledge/'+selected.id+'/download'} target="_blank" rel="noreferrer">下载原文件</a>}</div>}{/^https?:\/\//.test(selected.sourceUrl)&&<a href={selected.sourceUrl} target="_blank" rel="noreferrer" className="source-link">查看官方来源 <ArrowRight24Regular/></a>}</section></div>}
    {showAdd&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="提交知识或经验案例"><div className="modal-header"><div><h2>提交知识 / 经验案例</h2><p>案例先标记为待法务审核，不直接作为法律引用。</p></div><Button onClick={()=>setShowAdd(false)}>取消</Button></div><form onSubmit={save}><label className="field"><span>标题</span><Input required value={newTitle} onChange={(_,d)=>setNewTitle(d.value)} placeholder="例如：门卫代收争议的现场处理记录"/></label><div className="form-grid"><label className="field"><span>分类</span><select value={newType} onChange={e=>setNewType(e.target.value)}>{['历史案例','内部SOP','文书模板','行业规则','法律法规'].map(t=><option key={t}>{t}</option>)}</select></label><label className="field"><span>版本 / 日期</span><Input required value={version} onChange={(_,d)=>setVersion(d.value)}/></label></div><label className="field"><span>来源链接（法律法规与行业规则必填）</span><Input type="url" value={url} onChange={(_,d)=>setUrl(d.value)} required={newType==='法律法规'||newType==='行业规则'} placeholder="https://…"/></label><label className="field"><span>经验正文 / 事实摘要</span><Textarea required={!file} minLength={10} maxLength={30000} value={content} rows={7} onChange={(_,d)=>setContent(d.value)} placeholder="写清发生经过、已核实证据、处理动作、结果和仍待核验事项；不要写身份证号等无关敏感信息。"/></label><label className="knowledge-file-input"><ArrowUpload24Regular/><span>{file?file.name:'可选：上传经验记录原文件（TXT、CSV、PDF、DOCX或图片）'}</span><input type="file" accept=".txt,.md,.csv,.pdf,.docx,image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><div className="form-footer"><span>创建人：{user.name} · {user.role==='legal'?'法务可审核并发布':'提交后由法务审核'}</span><Button type="submit" appearance="primary" disabled={saving}>{saving?'保存中…':'提交到知识库'}</Button></div></form></section></div>}
  </>;
}
